### ISSUE TITLE
Exception: Unable to load asset: brazil_uf.json

### ISSUE THREAD

**Issue by yc-codes** [caduandrade/mapchart_flutter#1]
Trying to run `example` but showing this error
was testing on android 11

**Comment by yc-codes** [comment]
submitted pull request, can fix this issue #2

**Comment by caduandrade** [comment]
You are right, in fact, it is not loading on Android. I was testing only on the Web. I also noticed that on Android, a click on a geometry works as an "eternal hover" keeping the geometry highlighted. The selection feature is still on my TODO list but it looks like it "has already been implemented" :-). I will see that too. Thank you, I will accept the MR.
